/*
 * r2h_extmodule_temp_in_device_buffer_address.h
 *
 *  Created on: 2018-7-12
 *      Author: CrazyHein
 */

#ifndef R2H_EXTMODULE_TEMP_IN_DEVICE_BUFFER_ADDRESS_H_
#define R2H_EXTMODULE_TEMP_IN_DEVICE_BUFFER_ADDRESS_H_

//X Y Signals
#define R2H_TI_DEVICE_X_READY_FLAG									(0x00)
#define R2H_TI_DEVICE_X_OP_CONDITION_SET_OK							(0x09)
#define R2H_TI_DEVICE_X_OFFSETGAIN_MODE								(0x0A)
#define R2H_TI_DEVICE_X_CHANNEL_CHANGE_OK							(0x0B)
#define R2H_TI_DEVICE_X_DISCONNECTION_DETECTION						(0x0C)
#define R2H_TI_DEVICE_X_ALERT_FLAG									(0x0D)
#define R2H_TI_DEVICE_X_CONV_COMPLETED								(0x0E)
#define R2H_TI_DEVICE_X_ERROR_FLAG									(0x0F)

#define R2H_TI_DEVICE_Y_OP_CONDITION_SET_REQ						(0x09)
#define R2H_TI_DEVICE_Y_USER_RANGE_WRITE_REQ						(0x0A)
#define R2H_TI_DEVICE_Y_CHANNEL_CHANGE_REQ							(0x0B)
#define R2H_TI_DEVICE_Y_ERROR_CLR_REQ								(0x0F)



//Buffer Memory
#define R2H_TI_DEVICE_BUFM_LATEST_ERROR_CODE						(0)
#define R2H_TI_DEVICE_BUFM_LATEST_ERROR_ADDRESS_OF_HISTORY			(1)
#define R2H_TI_DEVICE_BUFM_LATEST_ALARM_CODE						(2)
#define R2H_TI_DEVICE_BUFM_LATEST_ALARM_ADDRESS_OF_HISTORY			(3)

#define R2H_TI_DEVICE_BUFM_PV_UPPER_LIMIT_ALARM						(36)
#define R2H_TI_DEVICE_BUFM_PV_LOWER_LIMIT_ALARM						(37)
#define R2H_TI_DEVICE_BUFM_RATE_UPPER_LIMIT_ALARM					(38)
#define R2H_TI_DEVICE_BUFM_RATE_LOWER_LIMIT_ALARM					(39)
#define R2H_TI_DEVICE_BUFM_DISCONNECTION_DETECTION_FLAG				(41)
#define R2H_TI_DEVICE_BUFM_CONV_COMPLETED_FLAG						(42)

#define R2H_TI_DEVICE_BUFS_COLD_JUNCTION_COMPENSATION				(298)
#define R2H_TI_DEVICE_BUFS_DISCONNECTION_DETECTION_AUTO_CLR			(303)

#define R2H_TI_DEVICE_CHANNEL_BUFFER_SIZE_IN_WORD					(200)

#define R2H_TI_DEVICE_BUFM_CH0_MEASURED_VALUE						(400)
#define R2H_TI_DEVICE_BUFM_CH0_SCALING_VALUE						(402)

#define R2H_TI_DEVICE_BUFS_CH0_CONV_ENABLE							(500)
#define R2H_TI_DEVICE_BUFS_CH0_AVERAGE_METHOD_SPEC					(501)
#define R2H_TI_DEVICE_BUFS_CH0_AVERAGE_METHOD_DATA					(502)

#define R2H_TI_DEVICE_BUFS_CH0_PV_ALARM_FUNCTION					(512)
#define R2H_TI_DEVICE_BUFS_CH0_RATE_ALARM_FUNCTION					(513)
#define R2H_TI_DEVICE_BUFS_CH0_PV_ALARM_UPPER_UPPER_LIMIT			(514)
#define R2H_TI_DEVICE_BUFS_CH0_PV_ALARM_UPPER_LOWER_LIMIT			(516)
#define R2H_TI_DEVICE_BUFS_CH0_PV_ALARM_LOWER_UPPER_LIMIT			(518)
#define R2H_TI_DEVICE_BUFS_CH0_PV_ALARM_LOWER_LOWER_LIMIT			(520)
#define R2H_TI_DEVICE_BUFS_CH0_RATE_ALARM_DETECTION_CYCLE			(522)
#define R2H_TI_DEVICE_BUFS_CH0_RATE_ALARM_UPPER_LIMIT				(524)
#define R2H_TI_DEVICE_BUFS_CH0_RATE_ALARM_LOWER_LIMIT				(526)
#define R2H_TI_DEVICE_BUFS_CH0_DISCONNECTION_DETECTION				(530)
#define R2H_TI_DEVICE_BUFS_CH0_CONVERSION_AT_DISCONNECTION			(531)
#define R2H_TI_DEVICE_BUFS_CH0_CONVERSION_VALUE_AT_DISCONNECTION	(532)

#define R2H_TI_DEVICE_BUFS_CH0_SCALE_ENABLE							(546)
#define R2H_TI_DEVICE_BUFS_CH0_SCALE_RANGE_UPPER_LIMIT				(548)
#define R2H_TI_DEVICE_BUFS_CH0_SCALE_RANGE_LOWER_LIMIT				(550)
#define R2H_TI_DEVICE_BUFS_CH0_SCALE_WIDTH_UPPER_LIMIT				(552)
#define R2H_TI_DEVICE_BUFS_CH0_SCALE_WIDTH_LOWER_LIMIT				(554)
#define R2H_TI_DEVICE_BUFS_CH0_RANGE_SETTING						(598)


#define R2H_TI_DEVICE_BUFM_ERROR_HISTORY_HEAD						(3600)
#define R2H_TI_DEVICE_BUFM_ALARM_HISTORY_HEAD						(3760)

#endif /* R2H_EXTMODULE_TEMP_IN_DEVICE_BUFFER_ADDRESS_H_ */
