/*
 * r2h_ilink_expression_def.h
 *
 *  Created on: 2020-3-26
 *      Author: CrazyHein
 */

#ifndef R2H_ILINK_EXPRESSION_DEF_H_
#define R2H_ILINK_EXPRESSION_DEF_H_

namespace R2H_ILINK
{
	typedef enum EXPRESSION_ELEMENT_TYPE
	{
		EXPRESSION_ELEMENT_TYPE_NONE					= -1,
		EXPRESSION_ELEMENT_TYPE_OBJECT_REFERENCE		= -2,
		EXPRESSION_ELEMENT_TYPE_IMMEDIATE_OPERAND		= -3,
		EXPRESSION_ELEMENT_TYPE_EVN_REFERENCE			= -4,
		EXPRESSION_ELEMENT_TYPE_OPERATOR				= -5,
		EXPRESSION_ELEMENT_TYPE_SPRITE					= -6
	}EXPRESSION_ELEMENT_TYPE_T;
	
	typedef enum ENV_VARIABLE
	{
		ENV_VARIABLE_NONE				= 0,
		ENV_VARIABLE_TICK				= 1,
		ENV_VARIABLE_STEP				= 2,
		ENV_VARIABLE_RETURN				= 3,
		ENV_VARIABLE_DEBUG				= 4,
		ENV_VARIABLE_USER				= 5
	}ENV_VARIABLE_T;
	
	typedef enum OPERATOR_NAME
	{
		OPERATOR_NAME_ADD					= 0,
		OPERATOR_NAME_SUBTRACT				= 1,
		OPERATOR_NAME_MULTIPLY				= 2,
		OPERATOR_NAME_DIVIDE				= 3,
		OPERATOR_NAME_LEFT_PARENTHESIS		= 4,
		OPERATOR_NAME_RIGHT_PARENTHESIS		= 5,
		OPERATOR_NAME_TERMINAL				= 6
	}OPERATOR_NAME_T;

	typedef enum SPRITE_FUNCTION
	{
		SPRITE_FUNCTION_UNDEFINED			= 0x0000,
		SPRITE_FUNCTION_LINEAR				= 0x0001,
		SPRITE_FUNCTION_MOD					= 0x0002,
		
		SPRITE_FUNCTION_SIN					= 0x0003,
		SPRITE_FUNCTION_COS					= 0x0004,
	}SPRITE_FUNCTION_T;

#define MAX_LAYER_OF_EMBEDDED_SPRITE_FUNCTION				(3)

#define SPRITE_FUNCTION_UNDEFINED_NAME						("UNDEFINED")
#define SPRITE_FUNCTION_LINEAR_NAME							("LINEAR")
#define SPRITE_FUNCTION_MOD_NAME							("MOD")
	
#define SPRITE_FUNCTION_SIN_NAME							("SIN")
#define SPRITE_FUNCTION_COS_NAME							("COS")
	
#define SPRITE_FUNCTION_LINEAR_PARAMETER_SIZE				(3)
#define SPRITE_FUNCTION_MOD_PARAMETER_SIZE					(2)
#define SPRITE_FUNCTION_SIN_PARAMETER_SIZE					(3)
#define SPRITE_FUNCTION_COS_PARAMETER_SIZE					(3)
}



#endif /* R2H_ILINK_EXPRESSION_DEF_H_ */
