/*
 * r2h_extmodule_r12ccpu_ecat_device_buffer_address.h
 *
 *  Created on: 2018-11-1
 *      Author: CrazyHein
 */

#ifndef R2H_EXTMODULE_R12CCPU_ECAT_DEVICE_BUFFER_ADDRESS_H_
#define R2H_EXTMODULE_R12CCPU_ECAT_DEVICE_BUFFER_ADDRESS_H_

#define R2H_R12CCPU_ECAT_DEVICE_BUF_MASTER_DIAGNOSTIC_INFO				(0)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_1ST_SLAVE_NODE_ADDRESS				(32)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_INPUT_DATA_OFFSET					(544)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_INPUT_DATA_SIZE_IN_BIT				(545)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_OUTPUT_DATA_OFFSET					(1568)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_OUTPUT_DATA_SIZE_IN_BIT				(1569)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_SLAVE_DIAGNOSTIC_INFO				(2592)

#define R2H_R12CCPU_ECAT_DEVICE_BUF_SDO_COMPLETED_COMMAND				(11882)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_SDO_UPLOAD_SLAVE_ADDRESS			(11883)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_SDO_UPLOAD_INDEX					(11884)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_SDO_UPLOAD_SUB_INDEX				(11885)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_SDO_UPLOAD_DATA_SIZE				(11886)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_SDO_UPLOAD_DATA_POINTER				(11888)

#define R2H_R12CCPU_ECAT_DEVICE_BUF_INPUT_DATA_READ_REQUEST				(3104)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_OUTPUT_DATA_READ_RESPONSE			(3105)
#define R2H_R12CCPU_ECAT_DEVICE_BUF_INPUT_DATA_POINTER					(3106)

#define R2H_R12CCPU_ECAT_HOST_BUF_MASTER_CONTROL_INFO					(0)
#define R2H_R12CCPU_ECAT_HOST_BUF_INPUT_DATA_READ_RESPONSE				(32)
#define R2H_R12CCPU_ECAT_HOST_BUF_OUTPUT_DATA_READ_REQUEST				(33)
#define R2H_R12CCPU_ECAT_HOST_BUF_OUTPUT_DATA_POINTER					(34)

#define R2H_R12CCPU_ECAT_HOST_BUF_SDO_CONTROL_COMMAND					(11882)
#define R2H_R12CCPU_ECAT_HOST_BUF_SDO_TARGET_SLAVE_ADDRESS				(11883)
#define R2H_R12CCPU_ECAT_HOST_BUF_SDO_TARGET_INDEX						(11884)
#define R2H_R12CCPU_ECAT_HOST_BUF_SDO_TARGET_SUB_INDEX					(11885)
#define R2H_R12CCPU_ECAT_HOST_BUF_SDO_DOWNLOAD_DATA_SIZE				(11886)
#define R2H_R12CCPU_ECAT_HOST_BUF_SDO_DOWNLOAD_DATA_POINTER				(11888)

#define R2H_R12CCPU_ECAT_DEVICE_MAX_INPUT_DATA_SIZE_IN_WORD				(11881-3106+1)
#define R2H_R12CCPU_ECAT_DEVICE_MAX_SDO_UPLOAD_SIZE_IN_WORD				(40)
#define R2H_R12CCPU_ECAT_HOST_MAX_OUTPUT_DATA_SIZE_IN_WORD				(11881-34+1)
#define R2H_R12CCPU_ECAT_HOST_MAX_SDO_DOWNLOAD_SIZE_IN_WORD				(40)
#define R2H_R12CCPU_ECAT_DEVICE_MAX_QUANTITY_OF_SLAVE_NODE				(512)


#endif /* R2H_EXTMODULE_R12CCPU_ECAT_DEVICE_BUFFER_ADDRESS_H_ */
