/*
 * r2h_extmodule_dn_device_buffer_address.h
 *
 *  Created on: 2018-8-3
 *      Author: CrazyHein
 */

#ifndef R2H_EXTMODULE_DN_DEVICE_BUFFER_ADDRESS_H_
#define R2H_EXTMODULE_DN_DEVICE_BUFFER_ADDRESS_H_

#define R2H_DN_DEVICE_X_WATCHDOG_TIMER_ERROR							(0x00)
#define R2H_DN_DEVICE_X_IO_COMMUNICATING								(0x01)
#define R2H_DN_DEVICE_X_MESSAGE_COMMUNICATION_COMPLETION				(0x02)
#define R2H_DN_DEVICE_X_MASTER_FUNCTION_ERROR_SET_SIGNAL				(0x03)
#define R2H_DN_DEVICE_X_SLAVE_DOWN_SIGNAL								(0x04)
#define R2H_DN_DEVICE_X_MESSAGE_COMMUNICATION_ERROR						(0x05)
#define R2H_DN_DEVICE_X_PARAMETER_SAVING								(0x06)
#define R2H_DN_DEVICE_X_PARAMETER_SAVE_COMPLETION						(0x07)
#define R2H_DN_DEVICE_X_SLAVE_FUNCTION_ERROR_SET_SIGNAL					(0x08)
#define R2H_DN_DEVICE_X_HARDWARE_TESTING								(0x0A)
#define R2H_DN_DEVICE_X_HARDWARE_TEST_COMPLETION						(0x0B)
#define R2H_DN_DEVICE_X_HARDWARE_TEST_ERROR								(0x0C)
#define R2H_DN_DEVICE_X_MODULE_READY									(0x0F)
#define R2H_DN_DEVICE_X_AUTO_CONFIGURATION_EXECUTING					(0x14)
#define R2H_DN_DEVICE_X_AUTO_CONFIGURATION_COMPLETION					(0x15)

#define R2H_DN_DEVICE_Y_IO_COMMUNICATION_REQUEST						(0x11)
#define R2H_DN_DEVICE_Y_MESSAGE_COMMUNICATION_REQUEST					(0x12)
#define R2H_DN_DEVICE_Y_MASTER_FUNCTION_ERROR_RESET_REQUEST				(0x13)
#define R2H_DN_DEVICE_Y_AUTO_CONFIGURATION_REQUEST						(0x15)
#define R2H_DN_DEVICE_Y_PARAMETER_SAVE_REQUEST							(0x17)
#define R2H_DN_DEVICE_Y_SLAVE_FUNCTION_ERROR_RESET_REQUEST				(0x18)

#define R2H_DN_DEVICE_BUF_MESSAGE_COMMUNICATION_COMMAND_HEAD			(272)	//272 to 287
#define R2H_DN_DEVICE_BUF_MESSAGE_COMMUNICATION_RESULT_HEAD				(288)	//288 to 303
#define R2H_DN_DEVICE_BUF_MESSAGE_COMMUNICATION_DATA					(304)	//304 to 423

#define R2H_DN_DEVICE_BUF_MASTER_FUNCTION_COMMUNICATION_STATUS			(432)
#define R2H_DN_DEVICE_BUF_MASTER_FUNCTION_ERROR_INFO					(433)

#define R2H_DN_DEVICE_BUF_MASTER_CONSTANT_SCAN							(471)
#define R2H_DN_DEVICE_BUF_1ST_SLAVE_NODE_PARAM							(472)

#define R2H_DN_DEVICE_BUF_NODE0_COMMUNICATION_ERROR_CODE				(1154)

#define R2H_DN_DEVICE_BUF_CURRENT_LINK_SCAN_TIME						(1532)
#define R2H_DN_DEVICE_BUF_MINIMUM_LINK_SCAN_TIME						(1533)
#define R2H_DN_DEVICE_BUF_MACIMUM_LINK_SCAN_TIME						(1534)

#define R2H_DN_DEVICE_BUF_MODEL_DISPLAY01								(1568)
#define R2H_DN_DEVICE_BUF_MODEL_DISPLAY23								(1569)
#define R2H_DN_DEVICE_BUF_MODEL_DISPLAY45								(1570)
#define R2H_DN_DEVICE_BUF_MODEL_DISPLAY67								(1571)
#define R2H_DN_DEVICE_BUF_MODEL_DISPLAY89								(1572)
#define R2H_DN_DEVICE_BUF_NODE_ADDRESS									(1573)
#define R2H_DN_DEVICE_BUF_MODE_SWITCH_NUMBER							(1574)

#define R2H_DN_DEVICE_BUF_OPERATION_SETTING_FOR_BUS_ERROR				(1586)
#define R2H_DN_DEVICE_BUF_DATA_CONSISTENCY_SETTING						(1587)
#define R2H_DN_DEVICE_BUF_DATA_CONSISTENCY_SETTING_STATUS				(1588)

#define R2H_DN_DEVICE_BUF_MASTER_RECEIVE_DATA_HEAD						(0x700)
#define R2H_DN_DEVICE_BUF_MASTER_TRANSMIT_DATA_HEAD						(0x900)

#define R2H_DN_DEVICE_BUF_SLAVE_RECEIVE_DATA_HEAD						(0xB00)
#define R2H_DN_DEVICE_BUF_SLAVE_TRANSMIT_DATA_HEAD						(0xC00)


#endif /* R2H_EXTMODULE_DN_DEVICE_BUFFER_ADDRESS_H_ */
