/*
 * r2h_extmodule_analog_out_device_buffer_address.h
 *
 *  Created on: 2018-7-9
 *      Author: CrazyHein
 */

#ifndef R2H_EXTMODULE_ANALOG_OUT_DEVICE_BUFFER_ADDRESS_H_
#define R2H_EXTMODULE_ANALOG_OUT_DEVICE_BUFFER_ADDRESS_H_

//X Y Signals
#define R2H_DA_DEVICE_X_READY_FLAG									(0x00)
#define R2H_DA_DEVICE_X_EXTERNAL_POWER_READY_FLAG					(0x07)
#define R2H_DA_DEVICE_X_OP_CONDITION_SET_OK							(0x09)
#define R2H_DA_DEVICE_X_OFFSETGAIN_MODE								(0x0A)
#define R2H_DA_DEVICE_X_CHANNEL_CHANGE_OK							(0x0B)
#define R2H_DA_DEVICE_X_SET_VALUE_COMPELTED							(0x0C)
#define R2H_DA_DEVICE_X_DISCONNECTION_DETECTION						(0x0D)
#define R2H_DA_DEVICE_X_ALERT_FLAG									(0x0E)
#define R2H_DA_DEVICE_X_ERROR_FLAG									(0x0F)


#define R2H_DA_DEVICE_Y_CH0_OUTPUT_ENABLE_FLAG						(0x01)
#define R2H_DA_DEVICE_Y_CH1_OUTPUT_ENABLE_FLAG						(0x02)
#define R2H_DA_DEVICE_Y_CH2_OUTPUT_ENABLE_FLAG						(0x03)
#define R2H_DA_DEVICE_Y_CH3_OUTPUT_ENABLE_FLAG						(0x04)
#define R2H_DA_DEVICE_Y_CH4_OUTPUT_ENABLE_FLAG						(0x05)
#define R2H_DA_DEVICE_Y_CH5_OUTPUT_ENABLE_FLAG						(0x06)
#define R2H_DA_DEVICE_Y_CH6_OUTPUT_ENABLE_FLAG						(0x07)
#define R2H_DA_DEVICE_Y_CH7_OUTPUT_ENABLE_FLAG						(0x08)

#define R2H_DA_DEVICE_Y_OP_CONDITION_SET_REQ						(0x09)
#define R2H_DA_DEVICE_Y_USER_RANGE_WRITE_REQ						(0x0A)
#define R2H_DA_DEVICE_Y_CHANNEL_CHANGE_REQ							(0x0B)
#define R2H_DA_DEVICE_Y_VALUE_CHANGE_REQ							(0x0C)
#define R2H_DA_DEVICE_Y_ALERT_CLR_REQ								(0x0E)
#define R2H_DA_DEVICE_Y_ERROR_CLR_REQ								(0x0F)

#define R2H_DA_DEVICE_BUFM_LATEST_ERROR_CODE						(0)
#define R2H_DA_DEVICE_BUFM_LATEST_ERROR_ADDRESS_OF_HISTORY			(1)

#define R2H_DA_DEVICE_BUFM_LATEST_ALARM_CODE						(2)
#define R2H_DA_DEVICE_BUFM_LATEST_ALARM_ADDRESS_OF_HISTORY			(3)

#define R2H_DA_DEVICE_BUFM_CH0_ALERT_OUTPUT_UPPER_LIMIT_FLAG		(36)
#define R2H_DA_DEVICE_BUFM_CH0_ALERT_OUTPUT_LOWER_LIMIT_FLAG		(37)
#define R2H_DA_DEVICE_BUFM_CH0_DISCONNECTION_DETECTION_FLAG			(38)

#define R2H_DA_DEVICE_CHANNEL_BUFFER_SIZE_IN_WORD					(200)

#define R2H_DA_DEVICE_BUFM_CH0_SETTING_VALUE_CHECK_CODE				(400)
#define R2H_DA_DEVICE_BUFC_CH0_DIGITAL_INPUT_VALUE					(460)
#define R2H_DA_DEVICE_BUFC_CH0_SHIFT_VALUE							(480)

#define R2H_DA_DEVICE_BUFS_CH0_CONV_ENABLE							(500)
#define R2H_DA_DEVICE_BUFS_CH0_SCALE_ENABLE							(502)
#define R2H_DA_DEVICE_BUFS_CH0_SCALE_UPPER_LIMIT					(504)
#define R2H_DA_DEVICE_BUFS_CH0_SCALE_LOWER_LIMIT					(506)
#define R2H_DA_DEVICE_BUFS_CH0_ALERT_OUTPUT_FUNC					(508)
#define R2H_DA_DEVICE_BUFS_CH0_RATE_CONTROL_FUNC					(509)
#define R2H_DA_DEVICE_BUFS_CH0_ALERT_OUTPUT_UPPER_LIMIT				(510)
#define R2H_DA_DEVICE_BUFS_CH0_ALERT_OUTPUT_LOWER_LIMIT				(512)
#define R2H_DA_DEVICE_BUFS_CH0_INCREASE_DIGITAL_LIMIT				(514)
#define R2H_DA_DEVICE_BUFS_CH0_DECREASE_DIGITAL_LIMIT				(516)
#define R2H_DA_DEVICE_BUFS_CH0_RANGE_SETTING						(598)


#define R2H_DA_DEVICE_BUFM_ERROR_HISTORY_HEAD						(3600)
#define R2H_DA_DEVICE_BUFM_ALARM_HISTORY_HEAD						(3760)


#endif /* R2H_EXTMODULE_ANALOG_OUT_DEVICE_BUFFER_ADDRESS_H_ */
