/*
 * r2h_task_amec_io_control_def.h
 *
 *  Created on: 2018-9-19
 *      Author: CrazyHein
 */

#ifndef R2H_TASK_AMEC_IO_CONTROL_DEF_H_
#define R2H_TASK_AMEC_IO_CONTROL_DEF_H_

#define R2H_TASK_RECIPE_PARSER_INDEX			(3)
#define R2H_TASK_RECIPE_PARSER_NAME				("R2H Recipe Parser Task")

typedef enum R2H_TASK_RECIPE_PARSER_HOST_COMMAND
{
	R2H_TASK_RECIPE_PARSER_NO_COMMAND			= 0x00000000,
	R2H_TASK_RECIPE_PARSER_TERMINATE			= 0x00000001,
	R2H_TASK_RECIPE_PARSER_NEW_RECIPE			= 0x00000002,
	__R2H_TASK_RECIPE_PARSER_HOST_COMMAND 		= 0xFFFFFFFF
}R2H_TASK_RECIPE_PARSER_HOST_COMMAND_T;



#endif /* R2H_TASK_AMEC_IO_CONTROL_DEF_H_ */
