/*
 * r2h_extmodule_temp_ctl_device_buffer_address.h
 *
 *  Created on: 2018-7-19
 *      Author: CrazyHein
 */

#ifndef R2H_EXTMODULE_TEMP_CTL_DEVICE_BUFFER_ADDRESS_H_
#define R2H_EXTMODULE_TEMP_CTL_DEVICE_BUFFER_ADDRESS_H_

//X Y Signals
#define R2H_TC_DEVICE_X_READY_FLAG									(0x00)
#define R2H_TC_DEVICE_X_OPERATION_MODE_STATUS						(0x01)
#define R2H_TC_DEVICE_X_ERROR_FLAG									(0x02)
#define R2H_TC_DEVICE_X_HARDWARE_ERROR_FLAG							(0x03)
#define R2H_TC_DEVICE_X_CH0_AT_STATUS								(0x04)
#define R2H_TC_DEVICE_X_CH1_AT_STATUS								(0x05)
#define R2H_TC_DEVICE_X_CH2_AT_STATUS								(0x06)
#define R2H_TC_DEVICE_X_CH3_AT_STATUS								(0x07)
#define R2H_TC_DEVICE_X_SETTING_BACKUP_OK							(0x08)
#define R2H_TC_DEVICE_X_DEFAULT_WRITE_OK							(0x09)
#define R2H_TC_DEVICE_X_SETTING_BACKUP_ERROR						(0x0A)
#define R2H_TC_DEVICE_X_SETTING_CHANGE_COMPLETION					(0x0B)
#define R2H_TC_DEVICE_X_CH0_ALERT_FLAG								(0x0C)
#define R2H_TC_DEVICE_X_CH1_ALERT_FLAG								(0x0D)
#define R2H_TC_DEVICE_X_CH2_ALERT_FLAG								(0x0E)
#define R2H_TC_DEVICE_X_CH3_ALERT_FLAG								(0x0F)


#define R2H_TC_DEVICE_Y_OPERATION_MODE_COMMAND						(0x01)
#define R2H_TC_DEVICE_Y_ERROR_RESET_COMMAND							(0x02)
#define R2H_TC_DEVICE_Y_CH0_AT_COMMAND								(0x04)
#define R2H_TC_DEVICE_Y_CH1_AT_COMMAND								(0x05)
#define R2H_TC_DEVICE_Y_CH2_AT_COMMAND								(0x06)
#define R2H_TC_DEVICE_Y_CH3_AT_COMMAND								(0x07)
#define R2H_TC_DEVICE_Y_SETTING_BACKUP_COMMAND						(0x08)
#define R2H_TC_DEVICE_Y_DEFAULT_WRITE_COMMAND						(0x09)
#define R2H_TC_DEVICE_Y_SETTING_CHANGE_COMMAND						(0x0B)
#define R2H_TC_DEVICE_Y_CH0_PID_FORCE_STOP							(0x0C)
#define R2H_TC_DEVICE_Y_CH1_PID_FORCE_STOP							(0x0D)
#define R2H_TC_DEVICE_Y_CH2_PID_FORCE_STOP							(0x0E)
#define R2H_TC_DEVICE_Y_CH3_PID_FORCE_STOP							(0x0F)


//buffer memory
#define R2H_TC_DEVICE_BUFM_LATEST_ERROR_CODE							(0)
#define R2H_TC_DEVICE_BUFM_ERROR_BUFFER_ADDRESS							(1)
#define R2H_TC_DEVICE_BUFM_LATEST_ERROR_ADDRESS_OF_HISTORY				(2)
#define R2H_TC_DEVICE_BUFM_LATEST_ALARM_CODE							(3)
#define R2H_TC_DEVICE_BUFM_LATEST_ALARM_ADDRESS_OF_HISTORY				(4)


#define R2H_TC_DEVICE_BUFM_CONTROL_MODE									(37)
#define R2H_TC_DEVICE_BUFM_SAMPLE_CYCLE									(38)
#define R2H_TC_DEVICE_BUFM_AUTO_SETTING_AT_RANGE_CHANGE					(39)

#define R2H_TC_DEVICE_BUFM_TEMPERTURE_CONV_COMPLETION					(43)
#define R2H_TC_DEVICE_BUFM_MANUAL_MODE_SHIFT_COMPLETION					(44)
#define R2H_TC_DEVICE_BUFM_COLD_JUNCTION_TEMPERATURE					(45)
#define R2H_TC_DEVICE_BUFM_PID_CONSTANTS_READ_COMPLETION				(46)
#define R2H_TC_DEVICE_BUFM_PID_CONSTANTS_WRITE_COMPLETION				(47)
#define R2H_TC_DEVICE_BUFM_FF_VALUE_READ_COMPLETION						(48)

#define R2H_TC_DEVICE_BUFS_CONTROL_MODE									(300)//A set value discrepancy error (control mode) (error code: 1910H) occurs right after the control mode change.
#define R2H_TC_DEVICE_BUFS_SAMPLE_CYCLE									(301)//A set value discrepancy error (sampling cycle) (error code: 1930H) occurs right after the sampling cycle change.
#define R2H_TC_DEVICE_BUFS_AUTO_SETTING_AT_RANGE_CHANGE					(302)
#define R2H_TC_DEVICE_BUFS_SV_VAR_LIMITER								(303)
#define R2H_TC_DEVICE_BUFS_CONTROL_OUTPUT_CYCLE_UNIT					(304)//A set value discrepancy error (control output cycle unit selection setting) (error code: 1920H) occurs right after the control output cycle unit selection setting change. 
#define R2H_TC_DEVICE_BUFS_MOVING_AVG_PROCESSING						(305)
#define R2H_TC_DEVICE_BUFS_PID_CONTINUATION_FLAG						(306)
#define R2H_TC_DEVICE_BUFS_TRANSISTOR_ON_DELAY_TIME						(307)//The setting range is 0 or 1 to 50 (10 to 500ms). When 0 has been set, ON delay output flag is not set to 1 (ON).
#define R2H_TC_DEVICE_BUFS_MV_RESOLUTION_FOR_AO_MODULE					(308)
#define R2H_TC_DEVICE_BUFS_COLD_JUNCTION_COMPENSATION					(309)

#define R2H_TC_DEVICE_CHANNEL_BUFFER_SIZE_IN_WORD						(200)

#define R2H_TC_DEVICE_BUFM_CH0_DECIMAL_POINT_POSITION					(400)
#define R2H_TC_DEVICE_BUFM_CH0_ALERT_DEFINITION							(401)
#define R2H_TC_DEVICE_BUFM_CH0_TEMPERATURE_PROCESS_VALUE				(402)
#define R2H_TC_DEVICE_BUFM_CH0_MANIPULATED_VALUE						(403)
#define R2H_TC_DEVICE_BUFM_CH0_SET_VALUE								(406)
#define R2H_TC_DEVICE_BUFM_CH0_ANALOG_MANIPULATED_VALUE					(407)
#define R2H_TC_DEVICE_BUFM_CH0_MANIPULATED_VALUE_C						(408)
#define R2H_TC_DEVICE_BUFM_CH0_ANALOG_MANIPULATED_VALUE_C				(409)
#define R2H_TC_DEVICE_BUFM_CH0_SELF_TUNING_FLAG							(411)
#define R2H_TC_DEVICE_BUFM_CH0_TEMPERATURE_PROCESS_SCALED_VALUE			(412)
#define R2H_TC_DEVICE_BUFM_CH0_SIMULTANEOUS_RISE_PARAM_FLAG				(413)
#define R2H_TC_DEVICE_BUFM_CH0_SIMULTANEOUS_RISE_STATUS					(414)

#define R2H_TC_DEVICE_BUFM_CH0_FF_CTL_FORCED_START_STATUS				(415)
#define R2H_TC_DEVICE_BUFM_CH0_FF_VALUE_TUNING_FLAG						(416)
#define R2H_TC_DEVICE_BUFM_CH0_FF_CTL_READY_FLAG						(417)
#define R2H_TC_DEVICE_BUFM_CH0_FF_CTL_FORCED_START_READY_FLAG			(418)

#define R2H_TC_DEVICE_BUFC_CH0_SET_VALUE								(430)
#define R2H_TC_DEVICE_BUFC_CH0_PROPORTIONAL_BAND						(431)
#define R2H_TC_DEVICE_BUFC_CH0_INTEGRAL_TIME							(432)
#define R2H_TC_DEVICE_BUFC_CH0_DERIVATIVE_TIME							(433)
#define R2H_TC_DEVICE_BUFC_CH0_ALERT0_SET_VALUE							(434)
#define R2H_TC_DEVICE_BUFC_CH0_ALERT1_SET_VALUE							(435)
#define R2H_TC_DEVICE_BUFC_CH0_ALERT2_SET_VALUE							(436)
#define R2H_TC_DEVICE_BUFC_CH0_ALERT3_SET_VALUE							(437)
#define R2H_TC_DEVICE_BUFC_CH0_ANALOG_PROCESS_VALUE						(438)
#define R2H_TC_DEVICE_BUFC_CH0_PROPORTIONAL_BAND_C						(439)

#define R2H_TC_DEVICE_BUFC_CH0_MEM_PID_CONSTANTS_READ_COMMAND			(440)
#define R2H_TC_DEVICE_BUFC_CH0_MEM_FF_VALUE_READ_COMMAND				(441)

////////////////////////////////////////////////////////////////////////////////////////////////
#define R2H_TC_DEVICE_BUFC_CH0_HOLD_CLEAR_SETTING						(500)
#define R2H_TC_DEVICE_BUFC_CH0_INPUT_RANGE								(501)
#define R2H_TC_DEVICE_BUFS_CH0_UNUSED_SETTING							(502)
#define R2H_TC_DEVICE_BUFS_CH0_STOP_MODE_SETTING						(503)
#define R2H_TC_DEVICE_BUFS_CH0_CONTROL_OUTPUT_PERIOD					(504)
#define R2H_TC_DEVICE_BUFS_CH0_CONTROL_RESPONSE_PARAM					(505)
#define R2H_TC_DEVICE_BUFS_CH0_TEMP_RISE_COMPLETION_RANGE				(506)
#define R2H_TC_DEVICE_BUFS_CH0_TEMP_RISE_COMPLETION_SOAK				(507)
#define R2H_TC_DEVICE_BUFS_CH0_MVH_UPPER_LIMITER						(508)
#define R2H_TC_DEVICE_BUFS_CH0_MV_LOWER_LIMITER							(509)
#define R2H_TC_DEVICE_BUFS_CH0_MV_VARIATION_AMOUNT_LIMITER				(510)			
#define R2H_TC_DEVICE_BUFS_CH0_SV_UPPER_LIMITER							(511)
#define R2H_TC_DEVICE_BUFS_CH0_SV_LOWER_LIMITER							(512)
#define R2H_TC_DEVICE_BUFS_CH0_SV_RISE_RATE_LIMITER						(513)
#define R2H_TC_DEVICE_BUFS_CH0_SV_DROP_RATE_LIMITER						(514)
#define R2H_TC_DEVICE_BUFS_CH0_ACTION_MODE								(515)
#define R2H_TC_DEVICE_BUFS_CH0_SV_ADJUSTMENT_DEAD_BAND					(516)
#define R2H_TC_DEVICE_BUFS_CH0_MANUAL_RESET_AMOUNT						(517)
#define R2H_TC_DEVICE_BUFS_CH0_AUTO_MAN_MODE_SHIFT						(518)
#define R2H_TC_DEVICE_BUFS_CH0_MANUAL_MV_SETTING						(519)
#define R2H_TC_DEVICE_BUFS_CH0_TEMPERATURE_CONVERSION					(520)
#define R2H_TC_DEVICE_BUFS_CH0_MVC_UPPER_LIMITER						(521)
#define R2H_TC_DEVICE_BUFS_CH0_CONTROL_OUTPUT_PERIOD_C					(522)
#define R2H_TC_DEVICE_BUFS_CH0_COOLING_METHOD							(523)
#define R2H_TC_DEVICE_BUFS_CH0_HEATING_COOLING_OVERLAP_DEAD_BAND		(524)
#define R2H_TC_DEVICE_BUFS_CH0_DERIVATIVE_ACTION						(525)
#define R2H_TC_DEVICE_BUFS_CH0_SV_VARIATION_RATE_LIMITER_UNIT_TIME		(526)
#define R2H_TC_DEVICE_BUFS_CH0_PP_CTL_OUTPUT_NEUTRAL_BAND				(527)
#define R2H_TC_DEVICE_BUFS_CH0_PP_CTL_MOTOR_TIME						(528)
#define R2H_TC_DEVICE_BUFS_CH0_PP_CTL_INTEGRATION_OUTPUT_LIMIT			(529)
#define R2H_TC_DEVICE_BUFS_CH0_PP_CTL_VALVE_OPERATION_AT_STOP			(530)
#define R2H_TC_DEVICE_BUFS_CH0_PV_ALERT_DEAD_BAND						(531)
#define R2H_TC_DEVICE_BUFS_CH0_ALERT_DELAY								(532)
#define R2H_TC_DEVICE_BUFS_CH0_ALERT0_MODE								(533)
#define R2H_TC_DEVICE_BUFS_CH0_ALERT1_MODE								(534)
#define R2H_TC_DEVICE_BUFS_CH0_ALERT2_MODE								(535)
#define R2H_TC_DEVICE_BUFS_CH0_ALERT3_MODE								(536)
#define R2H_TC_DEVICE_BUFS_CH0_LOOP_DISCONNECTION_JUDGMEMT_TIME			(537)
#define R2H_TC_DEVICE_BUFS_CH0_LOOP_DISCONNECTION_DEAD_BAND				(538)
#define R2H_TC_DEVICE_BUFS_CH0_PV_RATE_ALARM_SWITCH						(539)
#define R2H_TC_DEVICE_BUFS_CH0_PV_RATE_ALARM_CYCLE						(540)
#define R2H_TC_DEVICE_BUFS_CH0_PV_RATE_ALARM_UPPER						(541)
#define R2H_TC_DEVICE_BUFS_CH0_PV_RATE_ALARM_LOWER						(542)
#define R2H_TC_DEVICE_BUFS_CH0_AT_MODE_SELECTION						(543)
#define R2H_TC_DEVICE_BUFS_CH0_AT_ERROR_JUDGMEMT_TIME					(544)
#define R2H_TC_DEVICE_BUFS_CH0_AT_LOOP_DISCONNECTION_DETECTION			(545)
#define R2H_TC_DEVICE_BUFS_CH0_AT_BIAS									(546)
#define R2H_TC_DEVICE_BUFS_CH0_AT_AUTOMATIC_BACKUP						(547)
#define R2H_TC_DEVICE_BUFS_CH0_SELF_TUNING_MODE							(548)
#define R2H_TC_DEVICE_BUFS_CH0_PV_SCALING_FUNCTION_SWITCH				(549)
#define R2H_TC_DEVICE_BUFS_CH0_PV_SCALING_UPPER_LIMIT					(550)
#define R2H_TC_DEVICE_BUFS_CH0_PV_SCALING_LOWER_LIMIT					(551)
#define R2H_TC_DEVICE_BUFS_CH0_PEAK_CURRENT_SUPPRESSION_GROUP			(552)
#define R2H_TC_DEVICE_BUFS_CH0_SIMULTANEOUS_RISE_GROUP					(553)
#define R2H_TC_DEVICE_BUFS_CH0_SIMULTANEOUS_RISE_GRADIENT				(554)
#define R2H_TC_DEVICE_BUFS_CH0_SIMULTANEOUS_RISE_DEAD_TIME				(555)
#define R2H_TC_DEVICE_BUFS_CH0_SIMULTANEOUS_RISE_AT_MODE				(556)
#define R2H_TC_DEVICE_BUFS_CH0_FF_CTL_DISTURBANCE_JUDGMENT				(557)
#define R2H_TC_DEVICE_BUFS_CH0_FF_CTL_SV_RETURN_ADJUSTMENT				(558)
#define R2H_TC_DEVICE_BUFS_CH0_FF_CTL_FORCED_START_SIGNAL				(559)
#define R2H_TC_DEVICE_BUFS_CH0_FF_VALUE									(560)
#define R2H_TC_DEVICE_BUFS_CH0_FEED_FORWARD_VALUE						(560)
#define R2H_TC_DEVICE_BUFS_CH0_FF_VALUE_TUNING_SELECTION				(561)
#define R2H_TC_DEVICE_BUFS_CH0_OVERSHOOT_SUPPRESSION_LEVEL				(562)
#define R2H_TC_DEVICE_BUFS_CH0_PV_PRIMARY_DELAY							(563)
#define R2H_TC_DEVICE_BUFS_CH0_SENSOR_CORRECTION_METHOD					(564)
#define R2H_TC_DEVICE_BUFS_CH0_SENSOR_CORRECTION_VALUE					(565)
#define R2H_TC_DEVICE_BUFS_CH0_NUMBER_OF_MOVING_AVERAGING				(572)
////////////////////////////////////////////////////////////////////////////////////////////////


#define R2H_TC_DEVICE_BUFM_ERROR_HISTORY_HEAD							(3600)
#define R2H_TC_DEVICE_BUFM_ALARM_HISTORY_HEAD							(3760)

#endif /* R2H_EXTMODULE_TEMP_CTL_DEVICE_BUFFER_ADDRESS_H_ */
