/*
 * r2h_task_pdo_interlock_def.h
 *
 *  Created on: Feb 9, 2022
 *      Author: HaihangRen
 */

#ifndef R2H_TASK_PDO_INTERLOCK_DEF_H_
#define R2H_TASK_PDO_INTERLOCK_DEF_H_


typedef enum R2H_TASK_PDO_INTERLOCK_LOGIC_ELEMENT_TYPE 
{
	R2H_TASK_PDO_INTERLOCK_LOGIC_OPERAND	= 0x01,
	R2H_TASK_PDO_INTERLOCK_LOGIC_EXPRESSION	= 0x02
}R2H_TASK_PDO_INTERLOCK_LOGIC_ELEMENT_TYPE_T;

typedef enum R2H_TASK_PDO_INTERLOCK_LOGIC_OPERATOR
{
	R2H_TASK_PDO_INTERLOCK_LOGIC_AND		= 0x01,
	R2H_TASK_PDO_INTERLOCK_LOGIC_OR			= 0x02,
	R2H_TASK_PDO_INTERLOCK_LOGIC_NOT		= 0x10,
	R2H_TASK_PDO_INTERLOCK_LOGIC_XOR		= 0x03,
	R2H_TASK_PDO_INTERLOCK_LOGIC_NAND		= 0x11,
	R2H_TASK_PDO_INTERLOCK_LOGIC_NOR		= 0x12,
}R2H_TASK_PDO_INTERLOCK_LOGIC_OPERATOR_T;


#endif /* R2H_TASK_PDO_INTERLOCK_DEF_H_ */
